# Generated by Django 4.1 on 2022-11-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemira_ff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cNo',
            field=models.IntegerField(default=0),
        ),
    ]
