# Generated by Django 4.1 on 2022-11-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemira_ff', '0003_alter_voteresult_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteresult',
            name='cType',
            field=models.IntegerField(choices=[(1, 'Bpm'), (2, 'Bem')], default=1),
        ),
    ]
