# Generated by Django 4.1 on 2022-11-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemira_ff', '0004_voteresult_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteresult',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
