# Generated by Django 4.1 on 2022-12-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemira_ff', '0006_alter_voteresult_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='npm',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='tokenField',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='voteresult',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pemira_ff.candidate'),
        ),
    ]
